### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by HighSec-org** [Eomm/verdaccio-static-token#1]
After installing the verdaccio-static-token via npm and starting veradaccio, it produces the error:

info --- plugin verdaccio-htpasswd successfully loaded (authentication)

info --- Configuring verdaccio-static-token

fatal--- uncaught exception, please report this

TypeError: (config || []).forEach is not a function

    at module.exports (/usr/local/lib/node_modules/verdaccio-static-token/index.js:10:18)

    at executePlugin (/usr/local/lib/node_modules/verdaccio/node_modules/@verdaccio/loaders/build/plugin-async-loader.js:166:12)

    at asyncLoadPlugin (/usr/local/lib/node_modules/verdaccio/node_modules/@verdaccio/loaders/build/plugin-async-loader.js:126:18)

    at async Auth.init (/usr/local/lib/node_modules/verdaccio/node_modules/@verdaccio/auth/build/auth.js:32:19)

    at async defineAPI (/usr/local/lib/node_modules/verdaccio/build/api/index.js:35:3)

    at async _default (/usr/local/lib/node_modules/verdaccio/build/api/index.js:107:10)

which seems to be an error with the plugin and not my configuration. The exact same config works if I remove the plugin.

**Comment by Eomm** [comment]
Which `verdaccio` version?

This plugin is tested on (the old) verdaccio v3, so I think it need some update to get it working on the latest verdaccio v6

**Comment by silverwind** [comment]
Current main branch works with verdaccio 6.0.5, but seems to break with 6.1.3 at least.

https://github.com/verdaccio/verdaccio/issues/5160 may be related.

**Comment by RomanIzvozchikov** [comment]
Try [verdaccio-static-access-token-middleware-plugin](https://github.com/wunderwerkio/verdaccio-static-access-token-middleware-plugin) instead of this plugin for static tokens. It works on my Verdaccio 5.33.0 deployment.
